;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        cua-delete-region
        cua-paste
        dabbrev-expand
        decrement-integer-at-point
        drag-stuff-up
        electric-newline-and-maybe-indent
        forward-sexp
        haskell-indentation-delete-backward-char
        increment-integer-at-point
        indent-for-tab-command
        kill-line-or-region
        markdown-cycle
        markdown-exdent-or-delete
        python-backspace
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        python-toggle-assert-style
        save-line-or-region
        smart-beginning-of-line
        upcase-region
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        ido-switch-buffer
        my/mark-all-like-this-in-defun
        my/mark-all-symbols-like-this-in-defun
        ))
