;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-delete-region
        cua-paste
        dabbrev-expand
        forward-sexp
        haskell-indentation-delete-backward-char
        indent-for-tab-command
        markdown-cycle
        markdown-exdent-or-delete
        python-backspace
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        save-line-or-region
        smart-beginning-of-line
        upcase-region
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        my/mark-all-like-this-in-defun
        ))
