;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dabbrev-expand
	my/mark-all-like-this-in-defun
	python-indent-dedent-line-backspace
	python-indent-electric-colon
	))

(setq mc/cmds-to-run-once
      '(
	))
