(defun python-auto-super ()
  (interactive)
  (let (methodname classname)
    (save-excursion
      (python-nav-beginning-of-defun)
      (back-to-indentation)
      (or (looking-at "def[ \t]+\\([a-zA-Z0-9_]+\\)")
          (error "Can't determine method name"))
      (setq methodname (match-string 1))
      (python-nav-backward-up-list)
      (or (looking-at "[ \t]*class[ \t]+\\([a-zA-Z0-9_]+\\)")
          (error "Can't determine class name"))
      (setq classname (match-string 1)))
    (insert (format "super(%s, self).%s()" classname methodname))
    (backward-char)))

(provide 'python-auto-super)
